import os

atomic_numbers = {
    "H": 1, "He": 2, "Li": 3, "Be": 4, "B": 5, "C": 6, "N": 7, "O": 8, "F": 9, "Ne": 10, 
    "Na": 11, "Mg": 12, "Al": 13, "Si": 14, "P": 15, "S": 16, "Cl": 17, "Ar": 18, "K": 19, 
    "Ca": 20, "Sc": 21, "Ti": 22, "V": 23, "Cr": 24, "Mn": 25, "Fe": 26, "Ni": 28, "Co": 27, 
    "Cu": 29, "Zn": 30, "Ga": 31, "Ge": 32, "As": 33, "Se": 34, "Br": 35, "Kr": 36, "Rb": 37, 
    "Sr": 38, "Y": 39, "Zr": 40, "Nb": 41, "Mo": 42, "Tc": 43, "Ru": 44, "Rh": 45, "Pd": 46, 
    "Ag": 47, "Cd": 48, "In": 49, "Sn": 50, "Sb": 51, "I": 52, "Te": 53, "Xe": 54, "Cs": 55, 
    "Ba": 56, "La": 57, "Ce": 58, "Pr": 59, "Nd": 60, "Pm": 61, "Sm": 62, "Eu": 63, "Gd": 64, 
    "Tb": 65, "Dy": 66, "Ho": 67, "Er": 68, "Tm": 69, "Yb": 70, "Lu": 71, "Hf": 72, "Ta": 73, 
    "W": 74, "Re": 75, "Os": 76, "Ir": 77, "Pt": 78, "Au": 79, "Hg": 80, "Tl": 81, "Pb": 82, 
    "Bi": 83, "Po": 84, "At": 85, "Rn": 86, "Fr": 87, "Ra": 88, "Ac": 89, "Th": 90, "Pa": 91, 
    "U": 92, "Np": 93, "Pu": 94, "Am": 95, "Cm": 96, "Bk": 97, "Cf": 98, "Es": 99, "Fm": 100, 
    "Md": 101, "No": 102, "Lr": 103, "Rf": 104, "Db": 105, "Sg": 106, "Bh": 107, "Hs": 108, 
    "Mt": 109, "Ds": 110, "Rg": 111, "Cn": 112, "Nh": 113, "Fl": 114, "Mc": 115, "Lv": 116, 
    "Ts": 117, "Og": 118, "X":0
}

#covalent atomic radii for elements in picometers (pm):
covalent_radii = {
    "H": 32, "He": 31, "Li": 128, "Be": 96, "B": 84, "C": 77, "N": 75, "O": 73, "F": 71, "Ne": 69,
    "Na": 166, "Mg": 141, "Al": 118, "Si": 111, "P": 107, "S": 105, "Cl": 102, "Ar": 106, "K": 203, "Ca": 176,
    "Sc": 160, "Ti": 146, "V": 134, "Cr": 127, "Mn": 139, "Fe": 126, "Ni": 124, "Co": 125, "Cu": 127, "Zn": 139,
    "Ga": 122, "Ge": 122, "As": 119, "Se": 116, "Br": 114, "Kr": 112, "Rb": 303, "Sr": 249, "Y": 211, "Zr": 160,
    "Nb": 146, "Mo": 139, "Tc": 135, "Ru": 139, "Rh": 139, "Pd": 137, "Ag": 144, "Cd": 150, "In": 144, "Sn": 141,
    "Sb": 139, "I": 133, "Te": 138, "Xe": 140, "Cs": 298, "Ba": 253, "La": 195, "Ce": 198, "Pr": 200, "Nd": 202,
    "Pm": 207, "Sm": 211, "Eu": 207, "Gd": 214, "Tb": 221, "Dy": 228, "Ho": 227, "Er": 229, "Tm": 230, "Yb": 231,
    "Lu": 174, "Hf": 159, "Ta": 146, "W": 139, "Re": 137, "Os": 136, "Ir": 136, "Pt": 139, "Au": 144, "Hg": 149,
    "Tl": 146, "Pb": 154, "Bi": 156, "Po": 140, "At": 150, "Rn": 150, "Fr": 250, "Ra": 215, "Ac": 180, "Th": 180,
    "Pa": 180, "U": 175, "Np": 175, "Pu": 175, "Am": 175, "Cm": 175, "Bk": 175, "Cf": 175, "Es": 175, "Fm": 175,
    "Md": 175, "No": 175, "Lr": 175, "Rf": 175, "Db": 175, "Sg": 175, "Bh": 175, "Hs": 175, "Mt": 175, "Ds": 175,
    "Rg": 175, "Cn": 175, "Nh": 175, "Fl": 175, "Mc": 175, "Lv": 175, "Ts": 175, "Og": 175, "X":80
}



# Function to parse CONTCAR files and collect unique elements
def collect_elements_from_contcar(file_path):
    elements = set()
    with open(file_path, 'r') as f:
        lines = f.readlines()
        for i, line in enumerate(lines):
            if i == 5:  # This line contains the element symbols
                elements.update(line.split())
    return elements

def collect_elements_from_directory(root_dir):
    all_elements = set()
    print("List of considered files are:")
    for subdir, _, files in os.walk(root_dir):
        for file in files:
            if (file.startswith("POSCAR") or file.startswith("CONTCAR")) and file.endswith(".vasp"):
                file_path = os.path.join(subdir, file)
                print(f"File: {file_path}")
                elements = collect_elements_from_contcar(file_path)
                all_elements.update(elements)
    sorted_elements = sorted(elements, key=lambda x: covalent_radii[x])  ## atomic_numbers, covalent_radii
    return sorted_elements

# Function to create the legend.vasp file
def create_legend_vasp(elements, cell_size=15.0):
    # Create a unit cell with a diagonal
    unit_cell = [[cell_size, 0, 0], [0, cell_size, 0], [0, 0, cell_size]]
    
    # Create the VASP file format
    with open('legend.vasp', 'w') as f:
        f.write("Generated by legend.py\n")
        f.write(" 1.0\n")
        for row in unit_cell:
            #f.write(f"    {' '.join(map(str, row))}\n")
            f.write(f"    {row[0]:.4f} {row[1]:.4f} {row[2]:.4f}\n")

        
        num_elem = len(elements)

        symbols = ''
        counts = ''
        for elem in elements:
            symbols += elem+"  "
            counts += " 1  "
        
        f.write(f"{symbols}\n")
        f.write(f"{counts}\n")
        f.write("Direct\n")
        
        dx = 0.8/num_elem  # distance between two elements
        for i in range(num_elem):
            x=0.1+i*dx
            #f.write(f"  {x}    {x}    {x}\n")
            f.write(f"{x:.8f}    {x:.8f}    {x:.8f}\n")


if __name__ == "__main__":
    root_dir = "."  # Change this to your target folder path
    unique_elements = collect_elements_from_directory(root_dir)
    create_legend_vasp(unique_elements)
    print()
    print(f"legend.vasp created with all elements.\n")

